[project]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "codes"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
requests = ">=2.32.3,<3"
